#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
  datasource:
    #url: "jdbc:h2:file:C:/data/spring-data-jpa"
    url: "jdbc:h2:mem:testdb"
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
      generate-ddl: true
  sql:
    init:
      mode: always

logging:
  level:
    org:
      springframework: INFO
    com:
      learningJPA:
        dSpringDataRepository: TRACE