#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: "jdbc:h2:file:C:/data/spring-data-jpa"
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create
      generate-ddl: true

logging:
  level:
    org:
      springframework: DEBUG
    hibernate:
      type: trace
    root: WARN
    com:
      learningJPA:
        dSpringDataRepository: TRACE
  pattern:
    console: "%clr(%d{dd-mon-yyyy E HH:mm:ss.SSS}){red} %clr(%-5p) %clr(%logger{0}){blue} %clr(%m){faint}%n"